services:
  sicei-api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env.dev

  postgres-dev:
    image: postgres:15
    container_name: fastapi_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sicei
    ports:
      - "5432:5432"
    volumes:
      - sicei_data:/var/lib/postgresql/data

volumes:
  sicei_data:
